/*
 * This source file was generated by the Gradle 'init' task
 */
package projeto;
import projeto.investimentos.*;
import projeto.sistemas.Carteira;

public class App {
    public static void main(String[] args) {
        // ---------------------------------------------------------
        
        Carteira carteira = new Carteira();
        carteira.cadastra("Ação", "PETR4", 1000);
        carteira.cadastra("Fii", "HGLG11", 100);
        carteira.cadastra("Criptomoeda", "BNB", 2000);
        carteira.resumo("PETR4");
        System.out.println("");
        carteira.resumo("HGLG11");
        System.out.println("");
        carteira.resumo("BNB");
    }
}
