/*
 * This source file was generated by the Gradle 'init' task
 */
package projeto;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputFilter.Config;
import java.io.Reader;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonDeserializer;
import java.lang.reflect.Type;


import projeto.investimentos.*;
import projeto.sistemas.Carteira;

public class App {
    private static Gson criarGson(){
        JsonDeserializer<FinancialAsset> eventoDeserializer = new JsonDeserializer<FinancialAsset>() {
            @Override
            public FinancialAsset deserialize(JsonElement json,Type typeOft, JsonDeserializationContext context){
                JsonObject jsonObject = json.getAsJsonObject();
                int tipo = jsonObject.get("tipo").getAsInt();

                if(tipo == 0){
                    return context.deserialize(jsonObject, Açao.class);
                }else if(tipo == 1) {
                    return context.deserialize(jsonObject, Fii.class);
                }else if(tipo == 2){
                    return context.deserialize(jsonObject, Criptomoeda.class);
                }else{
                    return context.deserialize(jsonObject, Açao.class);
                }
                
            }
        };
        return new GsonBuilder().registerTypeAdapter(FinancialAsset.class, eventoDeserializer).setPrettyPrinting().create();
    }
    public static void salvarCarteira(Carteira carteira){
        Gson gson =  criarGson();
        try{     
            FileWriter writer = new FileWriter("carteira.json");
            gson.toJson(carteira, writer);
            writer.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }

    public static Carteira carregaCarteira(Carteira carta){
        Gson gson = criarGson();
        try{
            Reader readerM = new FileReader("carteira.json");
            carta = gson.fromJson(readerM, Carteira.class);
        } catch (Exception e){
            e.printStackTrace();
        }

        return carta;
    }


    public static void main(String[] args) {
        // ---------------------------------------------------------
        Carteira carteira = new Carteira();
        carteira = carregaCarteira(carteira);

        carteira.atualizarInformacoes();
        carteira.resumo("PETR4");
        System.out.println("");
        carteira.resumo("HGLG11");
        System.out.println("");
        carteira.resumo("BNB");
        salvarCarteira(carteira);
        
    }
}
